export const POST_NOTES_REQUEST="POST_NOTES_REQUEST";
export const POST_NOTES_SUCCESS="POST_NOTES_SUCCESS";
export const POST_NOTES_FAILED = "POST_NOTES_FAILED";

export const GET_NOTES_REQUEST = "GET_NOTES_REQUEST";
export const GET_NOTES_SUCCESS = "GET_NOTES_SUCCESS";
export const GET_NOTES_FAILED = " GET_NOTES_FAILED";

export const DELETE_NOTES_REQUEST = "DELETE_NOTES_REQUEST";
export const DELETE_NOTES_SUCCESS = "DELETE_NOTES_SUCCESS";
export const DELETE_NOTES_FAILED = " DELETE_NOTES_FAILED";
